name: Integration

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - name: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.mv2/repository
        key: om-${{hashFiles('**/pom.xml')}}

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - run: mvn dependency:go-offline
    - name: Build
      run: mvn clean process-test-classes verify
    # TODO: needs to be replaced with Jacoco (Cobertura does not work with JDK 11+)
    # - name: cobertura
    #   run: mvn cobertura:cobertura
    - name: codecov
      run: |
        curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov
